name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install Front
        run: npm --prefix public install
      - name: Build Back
        run: npm --prefix functions install
      - name: Deploy to Firebase for Devfest Lille
        run: npx firebase-tools deploy -P default
        env:
          FIREBASE_TOKEN: ${{ secrets.DEVFEST_FIREBASE_TOKEN }}
      - name: Deploy to Firebase for Devfest Lille
        run: npx firebase-tools deploy -P cloudnord
        env:
          FIREBASE_TOKEN: ${{ secrets.CLOUDNORD_FIREBASE_TOKEN }}
